# Generated by Django 2.2.7 on 2019-11-28 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=25)),
                ('catalogNumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('xml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('series', models.CharField(max_length=25)),
                ('catalogNumber', models.CharField(max_length=50)),
                ('slots', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('props', models.CharField(max_length=200)),
                ('xml', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=25)),
                ('catalogNumber', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('isSafety', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('createdOn', models.DateTimeField()),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('catalogId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.Module')),
                ('chassisId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.Chassis')),
                ('projId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjModuleProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('chassisId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Chassis')),
                ('projId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Project')),
                ('projModuleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.ProjModule')),
            ],
        ),
        migrations.CreateModel(
            name='ProjChassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassisId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.Chassis')),
                ('projId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Project')),
            ],
        ),
    ]
