# Generated by Django 2.2.7 on 2019-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20191128_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='xml',
            field=models.TextField(null=True),
        ),
    ]
