# Generated by Django 2.2.7 on 2019-11-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20191129_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
