# Generated by Django 2.2.7 on 2019-11-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_auto_20191129_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='isChassis',
            field=models.BooleanField(default=False),
        ),
    ]
