# Generated by Django 2.2.7 on 2019-12-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_projchassis_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projmodule',
            name='chassisId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generator.ProjChassis'),
            preserve_default=False,
        ),
    ]
