# Generated by Django 2.2.7 on 2019-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20191202_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projchassis',
            old_name='chassisId',
            new_name='catalogId',
        ),
        migrations.RemoveField(
            model_name='projmodule',
            name='catalogId',
        ),
        migrations.RemoveField(
            model_name='projmodule',
            name='projId',
        ),
        migrations.AddField(
            model_name='projmodule',
            name='catalogDescription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projmodule',
            name='catalogNumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projmodule',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
