# Generated by Django 2.2.7 on 2019-12-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_auto_20191202_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmodule',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projmodule',
            name='parent',
            field=models.CharField(default='Local', max_length=100),
        ),
    ]
