# Generated by Django 2.2.7 on 2019-12-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_auto_20191207_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmodule',
            name='projId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generator.Project'),
            preserve_default=False,
        ),
    ]
