# Generated by Django 2.2.7 on 2019-12-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_projmodule_projid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projmodule',
            name='chassisId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.ProjChassis'),
        ),
    ]
