# Generated by Django 2.2.7 on 2019-12-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_auto_20191207_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmodule',
            name='moduleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Module'),
        ),
    ]
