# Generated by Django 2.2.7 on 2019-12-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_projmodule_moduleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmoduleprop',
            name='extra',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
