# Generated by Django 2.2.7 on 2019-12-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_auto_20191228_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='type2',
            new_name='catagory',
        ),
    ]
