# Generated by Django 2.2.7 on 2019-12-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_projmoduleprop_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projmoduleprop',
            name='extra',
        ),
    ]
