# Generated by Django 2.2.7 on 2019-12-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_auto_20191228_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.ModuleCatagory'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.ModuleType'),
        ),
    ]
