# Generated by Django 2.2.7 on 2019-12-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_auto_20191228_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='catagory',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
