# Generated by Django 2.2.7 on 2019-12-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_auto_20191228_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleCatagory',
        ),
        migrations.DeleteModel(
            name='ModuleType',
        ),
    ]
