# Generated by Django 2.2.7 on 2019-12-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_auto_20191228_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='projchassis',
            name='parent',
            field=models.CharField(default='Local', max_length=100),
        ),
    ]
