# Generated by Django 2.2.7 on 2019-12-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_projchassis_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmodule',
            name='comments',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
